export const exercisesConfig = {
  defaultExercises: [
    "Squat",
    "Bench Press",
    "Deadlift",
    "Overhead Press",
    "Barbell Row",
    "Pull-Up",
    "Push-Up",
    "Dip",
    "Lunge",
    "Leg Press",
    "Bicep Curl",
    "Tricep Extension",
    "Hamstring Curl",
    "Calf Raise",
    "Chest Fly",
    "Lat Pulldown",
    "Shoulder Lateral Raise",
    "Plank",
    "Sit-Up",
    "Leg Extension",
  ],
};
